### ISSUE TITLE
TODO 30/8

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#92]
- [x] Mailutskick om nya mailadressen + uppdateringar
- [x] presentationsmaterial studenttjänster
- [ ] git/uppgifter: disclaimer om att ordningen måste stämma för att inluppen skall stämma
- [x] studenttjänster/uppgifter felstavat 'fornamn.efternamn'.
- [x] Guide till rättning av uppgifter

**Comment by Kurogamu** [comment]
Felstavningen blev rättad häromdagen!
